### ISSUE TITLE
What's needed (dependencies) to compile DnsCrypt.Toolbox?

### ISSUE THREAD

**Issue by zt3ph4n** [bitbeans/DnsCrypt.Toolbox#2]
I'd like to compile this project with Visual Studio 2019 Community?
I imported it cloning through github. Asks for .NET SDK which i got installed. (.NET SDK 5.0 preview ed.)

Thanks/z

**Comment by bitbeans** [comment]
Try .NET SDK 3.1.x https://dotnet.microsoft.com/download/dotnet-core/3.1

**Comment by zt3ph4n** [comment]
Getting 11 errors;

--

Severity	Code	Description	Project	File	Line	Suppression State
Error		Assets file 'C:\Users\zt3ph\source\repos\DnsCrypt.Toolbox3\DnsCrypt.Models\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	DnsCrypt.Models			
Error		Assets file 'C:\Users\zt3ph\source\repos\DnsCrypt.Toolbox3\DnsCrypt.Tools\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	DnsCrypt.Tools			
Error		Assets file 'C:\Users\zt3ph\source\repos\DnsCrypt.Toolbox3\DnsCrypt.Blacklist\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	DnsCrypt.Blacklist			
Error		Assets file 'C:\Users\zt3ph\source\repos\DnsCrypt.Toolbox3\DnsCrypt.Configuration\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	DnsCrypt.Configuration			
Error		Assets file 'C:\Users\zt3ph\source\repos\DnsCrypt.Toolbox3\DnsCrypt.Measurement\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	DnsCrypt.Measurement			
Error		Assets file 'C:\Users\zt3ph\source\repos\DnsCrypt.Toolbox3\DnsCrypt.Stamps\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	DnsCrypt.Stamps			
Error		Assets file 'C:\Users\zt3ph\source\repos\DnsCrypt.Toolbox3\DnsCrypt.Blacklist.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	DnsCrypt.Blacklist.Tests			
Error		Assets file 'C:\Users\zt3ph\source\repos\DnsCrypt.Toolbox3\DnsCrypt.Configuration.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	DnsCrypt.Configuration.Tests			
Error		Assets file 'C:\Users\zt3ph\source\repos\DnsCrypt.Toolbox3\DnsCrypt.Measurement.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	DnsCrypt.Measurement.Tests			
Error		Assets file 'C:\Users\zt3ph\source\repos\DnsCrypt.Toolbox3\DnsCrypt.Stamps.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	DnsCrypt.Stamps.Tests			
Error		Assets file 'C:\Users\zt3ph\source\repos\DnsCrypt.Toolbox3\Measurement\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Measurement		

--

What should i install to solve these?

-
EDIT: Solved it.
